apiVersion: apps/v1
kind: Deployment 
metadata:
  name: producer
  namespace: confluent
spec: 
  template:
    metadata:
      name: producer
      labels:
        app: produce
    spec:
      containers:
      - name: producer
        image: zeenia/prod:latest
        volumeMounts:
        - name: client-properties-volume
          mountPath: /mnt/client.properties
          subPath: client.properties
      volumes:
      - name: client-properties-volume
        configMap:
          name: client-properties
          items:
            - key: "client.properties"
              path: "client.properties"
  replicas: 1
  selector: 
    matchLabels:
      app: produce

---
apiVersion: v1
kind: Service
metadata:
  name: producer
spec: 
  clusterIP: None

---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata: 
  name: role
  namespace: confluent
spec:
  name: role
  replicas: 1
  partitionCount: 1
  configs:
    cleanup.policy: "delete"
