apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
  namespace: confluent
  labels:
    app: postgres 
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: secret

