apiVersion: v1
kind: Service
metadata:
  name: openldap
  labels:
    app: ldap
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 389
    name: ldap
  - port: 636
    name: ldaps
  clusterIP: none
  selector:
    app: openldap